LARGURA_TELA = 1000
ALTURA_TELA = 800



LARGURA_CAMPO = 1280
                        # ESSAS DUAS AQUI AIDA VAMOS MUDAR PQ PRECISAMOS CENTRALIZAR O CAMPO TUDO CERTINHO
ALTURA_CAMPO = 1080 



FPS = 30

COR_GRAMADO = (55, 111, 50) # UM VERDE MEIO ESCURO PRA O GRAMADO
COR_LINHA = (255, 255, 255) # BRANCO PARA AS LINHAS
COR_TRAVE = (255, 255, 255) # BRANCO PARA AS TRAVES
COR_NEYMAR = (255, 255, 0)  # COR DO RETANGULO AMARELO PRA SER O NEY
COR_ZAGUEIRO = (255, 0, 0)  # COR DO RETANGULO VERMELHO ZAGUEIRO
COR_BOLA = (255, 255, 255)  # BRANCO DA BOLA

# CONFIGURAÇÕES PARA O GOL
LARGURA_GOL = 120
ALTURA_GOL = 40
POS_GOL_Y = 50
POS_GOL_X = (LARGURA_TELA // 2) - (LARGURA_GOL // 2) # PRA ELE FICAR EXATAMENTE NO CENTRO

# CONFIGURAÇÕES DA GRANDE ÁREA
LARGURA_AREA = 806
ALTURA_AREA = 330
POSICAO_X_AREA = (LARGURA_TELA // 2) - (LARGURA_AREA // 2)

# MEIA LUA DO CAMPO
POS_MEIO_CAMPO_Y = ALTURA_TELA - 5
LARGURA_ARCO = 180
ALTURA_ARCO = 140

ARCO_X = (LARGURA_TELA // 2) - (LARGURA_ARCO // 2)
ARCO_Y = POS_MEIO_CAMPO_Y - (ALTURA_ARCO // 2)

# VELOCIDADE DO NEYMAR
VELOCIDADE_NEY = 5
# VELOCIDADE DO ZAGUEIRO
VELOCIDADE_ZAG = 3

CONFIANCA_POR_DIFICULDADE = {
    
    'FACIL': 30,
    'MEDIO':20,       # ESSAS CONFIANCAS AQUI PODEM MUDAR DEPOIS CASO NECESSARIO
    'DIFICIL': 10
}

DRIBLES_CONFIG = {
    
    'PEDALADA': {'ganho': 15, 'chance_inicial': 0.70, 'chance_max': 0.90},
    '360': {'ganho': 25, 'chance_inicial': 0.50, 'chance_max': 0.80},    # MAIS OUTROS DADOS QUE PODEM MUDAR
    'LAMBRETA': {'ganho': 40, 'chance_inicial': 0.25, 'chance_max': 0.75}
}

# META PRA ACUMULAR A ESTRELA DURANTE A PARTIDA
META_ESTRELA = 100

# OBS.: DEPOIS PODEMOS IMPLEMENTAR UM SISTEMA PRA UMA PARTE DA ESTRELA DO 'NEY PRIME' JA VIM
# UM POUCO CARREGADA A DEPENDER DA DIFICULDADE

FORCA_CHUTE = 15 # A VELOCIDADE QUE A BOLA VAI SE MOVER NA TELA

###---coletaveis---###
COR_ESTRELA = (255, 255, 0)   # Amarelo Ney Prime
COR_CHUTEIRA = (255, 128, 0)  # Laranja Energia
TAMANHO_ITEM = 20             # Largura e altura do retangulo do item
TEMPO_CHUTEIRA = 4000          # Tempo de sumiço 0.5 milisegundos
