LARGURA_TELA = 800
ALTURA_TELA = 600
FPS = 30

COR_GRAMADO = (55, 111, 50) # UM VERDE MEIO ESCURO PRA O GRAMADO
COR_LINHA = (255, 255, 255) # BRANCO PARA AS LINHAS
COR_NEYMAR = (255, 255, 0)  # COR DO RETANGULO AMARELO PRA SER O NEY
COR_BOLA = (255, 255, 255)  # BRANCO DA BOLA


VELOCIDADE_NEY = 5

CONFIANCA_POR_DIFICULDADE = {
    
    'FACIL': 30,
    'MEDIO':20,       # ESSAS CONFIANCAS AQUI PODEM MUDAR DEPOIS CASO NECESSARIO
    'DIFICIL': 10
}

DRIBLES_CONFIG = {
    
    'PEDALADA': {'ganho': 15, 'chance_inicial': 0.70, 'chance_max': 0.90},
    '360': {'ganho': 25, 'chance_inicial': 0.50, 'chance_max': 0.80},    # MAIS OUTROS DADOS QUE PODEM MUDAR
    'LAMBRETA': {'ganho': 40, 'chance_inicial': 0.25, 'chance_max': 0.75}
}

# META PRA ACUMULAR A ESTRELA DURANTE A PARTIDA
META_ESTRELA = 100

# OBS.: DEPOIS PODEMOS IMPLEMENTAR UM SISTEMA PRA UMA PARTE DA ESTRELA DO 'NEY PRIME' JA VIM
# UM POUCO CARREGADA A DEPENDER DA DIFICULDADE

FORCA_CHUTE = 15 # A VELOCIDADE QUE A BOLA VAI SE MOVER NA TELA

POS_GOL_Y = 80
POS_GOL_X = LARGURA_TELA // 2 # PRA ELE FICAR EXATAMENTE NO CENTRO E LA EM CIMA
